networks:
  another-chat-network:
    driver: bridge

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ${OLLAMA_CONTAINER_NAME:-ollama}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file: env.conf
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    networks:
      - another-chat-network
    environment:
      - TZ=${TIMEZONE:-Europe/Rome}
    healthcheck:
      disable: true

  web:
    build:
      context: ./web
      network: host
      args:
        - BUILDKIT_INLINE_CACHE=1
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    container_name: ${WEB_CONTAINER_NAME:-another-chat-web}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file: env.conf
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./web:/app
      - ${DATA_VOLUME:-./web/data}:/app/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - ollama
    networks:
      - another-chat-network
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - TZ=${TIMEZONE:-Europe/Rome}

volumes:
  ollama_data:
  documents_data: